# テンポラリファイルの削除コマンド
description="テンポラリファイルの削除コマンド"

prompt = """
# テンポラリファイルの削除コマンド

## Description: 概要

テンポラリファイルの削除コマンドです。
作業に際して、作成された一時ファイル（テンポラリファイル）を削除します。

------------------------------------------------------------------------------------

## Instruction: 指示

Follow these steps: 以下のステップで作業を実行してください。

1. **削除ファイルの確認**
   - TargetDirectory: 対象ディレクトリ `.gemini/tmp/`
   - Task: 一時ファイルの対象ファイルを確認する。ディレクトリを直接参照して、対象ファイルを見つけてください。
   - TaskDetail: ファイル一覧を回答してください。

2. **削除ファイルを削除する**
   - TargetDirectory: 対象ディレクトリ `.gemini/tmp/`
   - Task: ユーザーから承認が得られたら、対象ファイルを削除してください。

------------------------------------------------------------------------------------

## ImportantConstraints: 重要な制約事項

- プレースホルダーファイル `.keep` ファイルは削除しないでください。
- gitignored ファイルも対象にしてください。


"""