# エージェントタスクの実行コマンド
description="エージェントタスクの実行コマンド"

prompt = """
# エージェントタスクの実行コマンド

## Description: 概要
<!-- こちらにタスクの概要を端的に記載してください -->

------------------------------------------------------------------------------------
## Instruction: 指示

Follow these steps: 以下のステップで作業を実行してください。

こちらはカスタムスラッシュコマンドのテストです。

Hello, World と表示してください。

<!-- 
1. **業務委託メンバーの請求書を整理する**
   - 読み込んで実行: `.claude/commands/tasks/subtask.md`
   - 目的: 業務委託メンバーの請求書を整理（カテゴライズ）
 -->


"""